/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hape1bif;

import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 61klir1bif
 */
public class hauptfenster extends javax.swing.JFrame {

    /**
     * Creates new form sample
     */
    public hauptfenster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTabbedPane1 = new javax.swing.JTabbedPane();
                vertraegeTab = new javax.swing.JPanel();
                jScrollPane4 = new javax.swing.JScrollPane();
                jTable4 = new javax.swing.JTable();
                septemberTab = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                oktoberTab = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable2 = new javax.swing.JTable();
                novemberTab = new javax.swing.JPanel();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTable3 = new javax.swing.JTable();
                dezemberTab = new javax.swing.JPanel();
                jScrollPane5 = new javax.swing.JScrollPane();
                jTable5 = new javax.swing.JTable();
                januarTab = new javax.swing.JPanel();
                jScrollPane6 = new javax.swing.JScrollPane();
                jTable6 = new javax.swing.JTable();
                februarTab = new javax.swing.JPanel();
                jScrollPane7 = new javax.swing.JScrollPane();
                jTable7 = new javax.swing.JTable();
                menuBar = new javax.swing.JMenuBar();
                fileMenu = new javax.swing.JMenu();
                openMenuItem = new javax.swing.JMenuItem();
                saveMenuItem = new javax.swing.JMenuItem();
                saveAsMenuItem = new javax.swing.JMenuItem();
                settingsMenuItem = new javax.swing.JMenuItem();
                exitMenuItem = new javax.swing.JMenuItem();
                editMenu = new javax.swing.JMenu();
                connectMenuItem = new javax.swing.JMenuItem();
                readMenuItem = new javax.swing.JMenuItem();
                answerMenuItem = new javax.swing.JMenuItem();
                auswertenMenu = new javax.swing.JMenu();
                extrasMenu = new javax.swing.JMenu();
                importMenuItem = new javax.swing.JMenuItem();
                helpMenu = new javax.swing.JMenu();
                contentsMenuItem = new javax.swing.JMenuItem();
                aboutMenuItem = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jTable4.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane4.setViewportView(jTable4);

                javax.swing.GroupLayout vertraegeTabLayout = new javax.swing.GroupLayout(vertraegeTab);
                vertraegeTab.setLayout(vertraegeTabLayout);
                vertraegeTabLayout.setHorizontalGroup(
                        vertraegeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                );
                vertraegeTabLayout.setVerticalGroup(
                        vertraegeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(vertraegeTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                );

                jTabbedPane1.addTab("Verträge", vertraegeTab);

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Nr.", "Name", "Vorname", "Datum"
                        }
                ));
                jScrollPane1.setViewportView(jTable1);

                javax.swing.GroupLayout septemberTabLayout = new javax.swing.GroupLayout(septemberTab);
                septemberTab.setLayout(septemberTabLayout);
                septemberTabLayout.setHorizontalGroup(
                        septemberTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                );
                septemberTabLayout.setVerticalGroup(
                        septemberTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("September", septemberTab);

                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Nr.", "Name", "Vorname", "Datum"
                        }
                ));
                jScrollPane2.setViewportView(jTable2);

                javax.swing.GroupLayout oktoberTabLayout = new javax.swing.GroupLayout(oktoberTab);
                oktoberTab.setLayout(oktoberTabLayout);
                oktoberTabLayout.setHorizontalGroup(
                        oktoberTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                );
                oktoberTabLayout.setVerticalGroup(
                        oktoberTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Oktober", oktoberTab);

                jTable3.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Nr.", "Name", "Vorname", "Datum"
                        }
                ));
                jScrollPane3.setViewportView(jTable3);

                javax.swing.GroupLayout novemberTabLayout = new javax.swing.GroupLayout(novemberTab);
                novemberTab.setLayout(novemberTabLayout);
                novemberTabLayout.setHorizontalGroup(
                        novemberTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                );
                novemberTabLayout.setVerticalGroup(
                        novemberTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("November", novemberTab);

                jTable5.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Nr.", "Name", "Vorname", "Datum"
                        }
                ));
                jScrollPane5.setViewportView(jTable5);

                javax.swing.GroupLayout dezemberTabLayout = new javax.swing.GroupLayout(dezemberTab);
                dezemberTab.setLayout(dezemberTabLayout);
                dezemberTabLayout.setHorizontalGroup(
                        dezemberTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                );
                dezemberTabLayout.setVerticalGroup(
                        dezemberTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Dezember", dezemberTab);

                jTable6.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Nr.", "Name", "Vorname", "Datum"
                        }
                ));
                jScrollPane6.setViewportView(jTable6);

                javax.swing.GroupLayout januarTabLayout = new javax.swing.GroupLayout(januarTab);
                januarTab.setLayout(januarTabLayout);
                januarTabLayout.setHorizontalGroup(
                        januarTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                );
                januarTabLayout.setVerticalGroup(
                        januarTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Januar", januarTab);

                jTable7.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Nr.", "Name", "Vorname", "Datum"
                        }
                ));
                jScrollPane7.setViewportView(jTable7);

                javax.swing.GroupLayout februarTabLayout = new javax.swing.GroupLayout(februarTab);
                februarTab.setLayout(februarTabLayout);
                februarTabLayout.setHorizontalGroup(
                        februarTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                );
                februarTabLayout.setVerticalGroup(
                        februarTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Februar", februarTab);

                fileMenu.setMnemonic('f');
                fileMenu.setText("Datei");

                openMenuItem.setMnemonic('o');
                openMenuItem.setText("Öffnen");
                openMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                openMenuItemMouseClicked(evt);
                        }
                });
                openMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                openMenuItemActionPerformed(evt);
                        }
                });
                fileMenu.add(openMenuItem);

                saveMenuItem.setMnemonic('s');
                saveMenuItem.setText("Speichern");
                saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveMenuItemActionPerformed(evt);
                        }
                });
                fileMenu.add(saveMenuItem);

                saveAsMenuItem.setMnemonic('a');
                saveAsMenuItem.setText("Speicher als..");
                saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveAsMenuItemActionPerformed(evt);
                        }
                });
                fileMenu.add(saveAsMenuItem);

                settingsMenuItem.setText("Email Einstellungen");
                settingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                settingsMenuItemActionPerformed(evt);
                        }
                });
                fileMenu.add(settingsMenuItem);

                exitMenuItem.setMnemonic('x');
                exitMenuItem.setText("Beenden");
                exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                exitMenuItemActionPerformed(evt);
                        }
                });
                fileMenu.add(exitMenuItem);

                menuBar.add(fileMenu);

                editMenu.setMnemonic('e');
                editMenu.setText("Bearbeiten");

                connectMenuItem.setMnemonic('t');
                connectMenuItem.setText("Verbinden");
                connectMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                connectMenuItemActionPerformed(evt);
                        }
                });
                editMenu.add(connectMenuItem);

                readMenuItem.setMnemonic('y');
                readMenuItem.setText("Lesen");
                readMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                readMenuItemActionPerformed(evt);
                        }
                });
                editMenu.add(readMenuItem);

                answerMenuItem.setMnemonic('p');
                answerMenuItem.setText("Beantworten");
                answerMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                answerMenuItemActionPerformed(evt);
                        }
                });
                editMenu.add(answerMenuItem);

                menuBar.add(editMenu);

                auswertenMenu.setText("Auswerten");
                menuBar.add(auswertenMenu);

                extrasMenu.setText("Extras");

                importMenuItem.setText("Verträge importieren");
                extrasMenu.add(importMenuItem);

                menuBar.add(extrasMenu);

                helpMenu.setMnemonic('h');
                helpMenu.setText("Help");
                helpMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

                contentsMenuItem.setMnemonic('c');
                contentsMenuItem.setText("Contents");
                helpMenu.add(contentsMenuItem);

                aboutMenuItem.setMnemonic('a');
                aboutMenuItem.setText("About");
                helpMenu.add(aboutMenuItem);

                menuBar.add(helpMenu);

                setJMenuBar(menuBar);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents
               
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:

        Open o = new Open();
        o.setVisible(true);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:

        SaveAs s = new SaveAs();
        s.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void settingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsMenuItemActionPerformed
        //Dialog (Klick --> neues Fenster --> Eigenschaften)

        Settings s = new Settings();
        s.setVisible(true);
    }//GEN-LAST:event_settingsMenuItemActionPerformed

    private void connectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectMenuItemActionPerformed

    private void answerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerMenuItemActionPerformed

    private void openMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMenuItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_openMenuItemMouseClicked

    private void readMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readMenuItemActionPerformed
        // TODO add your handling code here:
        //open mails
        //2 Kästchen zur Auswahl (Bestätigung schicken , Fehlerbericht)
        //2 Button (Schließen, Speichern)
        //
        //Dann Dialog was geschickt wurde

    }//GEN-LAST:event_readMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hauptfenster().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenuItem aboutMenuItem;
        private javax.swing.JMenuItem answerMenuItem;
        private javax.swing.JMenu auswertenMenu;
        private javax.swing.JMenuItem connectMenuItem;
        private javax.swing.JMenuItem contentsMenuItem;
        private javax.swing.JPanel dezemberTab;
        private javax.swing.JMenu editMenu;
        private javax.swing.JMenuItem exitMenuItem;
        private javax.swing.JMenu extrasMenu;
        private javax.swing.JPanel februarTab;
        private javax.swing.JMenu fileMenu;
        private javax.swing.JMenu helpMenu;
        private javax.swing.JMenuItem importMenuItem;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JScrollPane jScrollPane6;
        private javax.swing.JScrollPane jScrollPane7;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable jTable2;
        private javax.swing.JTable jTable3;
        private javax.swing.JTable jTable4;
        private javax.swing.JTable jTable5;
        private javax.swing.JTable jTable6;
        private javax.swing.JTable jTable7;
        private javax.swing.JPanel januarTab;
        private javax.swing.JMenuBar menuBar;
        private javax.swing.JPanel novemberTab;
        private javax.swing.JPanel oktoberTab;
        private javax.swing.JMenuItem openMenuItem;
        private javax.swing.JMenuItem readMenuItem;
        private javax.swing.JMenuItem saveAsMenuItem;
        private javax.swing.JMenuItem saveMenuItem;
        private javax.swing.JPanel septemberTab;
        private javax.swing.JMenuItem settingsMenuItem;
        private javax.swing.JPanel vertraegeTab;
        // End of variables declaration//GEN-END:variables

    public File f;
}
